// Build script to auto-generate module declarations for unified commands
// This eliminates merge conflicts when agents add new command modules

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    #[allow(clippy::disallowed_methods)]
    let out_dir = env::var("OUT_DIR").unwrap();
    let commands_dir = "src/repl/unified_commands";

    // Tell Cargo to rerun this build script if the unified_commands directory changes
    println!("cargo:rerun-if-changed={commands_dir}");

    // Auto-generate module declarations for all command files
    let mut module_declarations = String::new();
    module_declarations.push_str("// Auto-generated module declarations - DO NOT EDIT MANUALLY\n");
    module_declarations
        .push_str("// This file is generated by build.rs to eliminate merge conflicts\n\n");

    // Core infrastructure modules (always included)
    module_declarations.push_str("// Core infrastructure\n");
    module_declarations.push_str("pub mod command;\n");
    module_declarations.push_str("pub mod dynamic_registry;\n");
    module_declarations.push_str("pub mod events;\n\n");

    // Auto-discover command modules
    module_declarations.push_str("// Auto-discovered command implementations\n");

    if let Ok(entries) = fs::read_dir(commands_dir) {
        let mut command_files = Vec::new();

        for entry in entries.flatten() {
            let path = entry.path();
            if let Some(file_name) = path.file_name() {
                let file_str = file_name.to_string_lossy();

                // Skip core files and include only command implementation files
                if file_str.ends_with(".rs")
                    && !file_str.starts_with("mod.")
                    && file_str != "command.rs"
                    && file_str != "dynamic_registry.rs"
                    && file_str != "events.rs"
                {
                    let module_name = file_str.trim_end_matches(".rs");
                    command_files.push(module_name.to_string());
                }
            }
        }

        // Sort for consistent output
        command_files.sort();

        for module_name in command_files {
            module_declarations.push_str(&format!("pub mod {module_name};\n"));
        }
    }

    // Add re-exports
    module_declarations.push_str("\n// Re-export main types\n");
    module_declarations.push_str("pub use command::{Command, CommandContext, ExecutionContext};\n");
    module_declarations.push_str("pub use dynamic_registry::{register_all_commands, CommandEntry, CommandFactory, DynamicCommandRegistry};\n");
    module_declarations.push_str("pub use events::{ModelEvent, YankType};\n");
    module_declarations.push_str("\n// Note: Individual command re-exports no longer needed -\n");
    module_declarations.push_str("// commands self-register using the inventory system\n");

    // Write the generated module file
    let dest_path = Path::new(&out_dir).join("generated_modules.rs");
    fs::write(&dest_path, module_declarations)
        .expect("Failed to write generated module declarations");

    println!(
        "Generated module declarations with {} command modules",
        fs::read_dir(commands_dir)
            .map(|entries| entries.count())
            .unwrap_or(0)
            - 3
    );
}
