name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.1.10)'
        required: true
        type: string
      source_branch:
        description: 'Source branch (default: develop)'
        required: false
        default: 'develop'
        type: string

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  create-release-branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    steps:
    - name: Validate version format
      run: |
        if ! echo "${{ github.event.inputs.version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "❌ Invalid version format. Please use semantic versioning (e.g., 0.1.10)"
          exit 1
        fi
        echo "✅ Version format is valid"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.source_branch }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create release branch
      run: |
        VERSION="${{ github.event.inputs.version }}"
        SOURCE_BRANCH="${{ github.event.inputs.source_branch }}"
        RELEASE_BRANCH="release/${VERSION}"
        
        echo "Creating release branch: $RELEASE_BRANCH from $SOURCE_BRANCH"
        
        # Check if release branch already exists
        if git ls-remote --exit-code --heads origin $RELEASE_BRANCH; then
          echo "❌ Release branch $RELEASE_BRANCH already exists"
          exit 1
        fi
        
        # Create and switch to release branch
        git checkout -b $RELEASE_BRANCH
        
        # Update version in Cargo.toml
        sed -i.bak "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
        rm Cargo.toml.bak
        
        # Update Cargo.lock
        cargo update --package webly
        
        # Commit version changes
        git add Cargo.toml Cargo.lock
        git commit -m "Prepare release $VERSION - Bump version and update Cargo.lock"
        
        # Push release branch
        git push origin $RELEASE_BRANCH
        
        echo "✅ Created release branch: $RELEASE_BRANCH"
        echo "✅ Updated version to: $VERSION"
        echo ""
        echo "Next steps:"
        echo "1. Release workflow will automatically run on this branch"
        echo "2. Test the release artifacts"
        echo "3. If successful, create a git tag: git tag v$VERSION && git push origin v$VERSION"
        echo "4. The release will be automatically merged back to main and develop"

    - name: Create Pull Request
      run: |
        VERSION="${{ github.event.inputs.version }}"
        SOURCE_BRANCH="${{ github.event.inputs.source_branch }}"
        RELEASE_BRANCH="release/${VERSION}"
        
        # Create PR for visibility
        gh pr create \
          --title "Release $VERSION" \
          --body "Release $VERSION prepared from $SOURCE_BRANCH. Version bumped and ready for testing." \
          --base develop \
          --head $RELEASE_BRANCH \
          --draft
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Summary
      run: |
        VERSION="${{ github.event.inputs.version }}"
        RELEASE_BRANCH="release/${VERSION}"
        
        echo "Release branch created successfully: $RELEASE_BRANCH"
        echo "Version: $VERSION"
        echo "Next: Monitor release workflow and create tag when ready"
